#!/bin/bash

OBJCLINT_LOCATION=/opt/local/bin/objclint-dispatcher.py

cat > /tmp/ObjclintResourcePlist.plist << EOL
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>rules</key>
        <dict>
            <key>.*</key>
            <dict>
                <key>omit</key>
                <true/>
                <key>weight</key>
                <real>10</real>
            </dict>
        </dict>
    </dict>
</plist>
EOL

/opt/local/bin/objclint-coordinator &>/dev/null&
sleep 1
/opt/local/bin/objclint-coordinator --check

if [ $? -gt 0 ]; then
    echo "Failed to start objclint-coordinator"
    exit 1
fi

xcodebuild \
    CC="$OBJCLINT_LOCATION"\
    CXX="$OBJCLINT_LOCATION"\
    CCFLAGS="-objclint-fake-cc"\
    CXXFLAGS="-objclint-fake-cxx"\
    LD="true"\
    LDPLUSPLUS="true"\
    LIBTOOL="true"\
    GCC_GENERATE_DEBUGGING_SYMBOLS=NO\
    GCC_PRECOMPILE_PREFIX_HEADER=NO\
    ONLY_ACTIVE_ARCH=YES\
    --resource-rules=/tmp/ObjclintResourceRules.plist\
    -PBXBuildsContinueAfterErrors=YES\
    -jobs 1\
    "$@"
